name: Run BEV Application in Anaconda Environment

on: [push]

jobs:
  run-bev-app:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Anaconda environment
      run: |
        source ~/anaconda3/etc/profile.d/conda.sh
        conda activate orthophoto

    - name: Check if port 8001 is in use
      run: |
        PID=$(lsof -t -i:8001 -sTCP:LISTEN) || true
        if [ -z "$PID" ]; then
          echo "No process found on port 8001. Proceeding to start the app."
        else
          echo "Killing process on port 8001 with PID $PID"
          kill $PID
        fi
    
    - name: Run app.py in orthophoto environment
      run: |
        source ~/anaconda3/etc/profile.d/conda.sh
        conda activate orthophoto
        python /home/dva4/DVA_LAB/models/BEV/app.py
