name: Run Detection Application in Anaconda Environment

on: [push]

jobs:
  run-detection-app:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Anaconda environment
      run: |
        source ~/anaconda3/etc/profile.d/conda.sh
        conda activate detection

    - name: Check if port 8002 is in use
      run: |
        PID=$(lsof -t -i:8002 -sTCP:LISTEN) || true
        if [ -z "$PID" ]; then
          echo "No process found on port 8002. Proceeding to start the app."
        else
          echo "Killing process on port 8002 with PID $PID"
          kill $PID
        fi
    
    - name: Run app.py in detection environment
      run: |
        source ~/anaconda3/etc/profile.d/conda.sh
        conda activate detection
        python /home/dva4/DVA_LAB/models/sahi_detection/app.py
