name: Run Refinement Application in Anaconda Environment

on: [push]

jobs:
  run-refinement-app:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Anaconda environment
      run: |
        source ~/anaconda3/etc/profile.d/conda.sh
        conda activate refinement

    - name: Check if port 8005 is in use
      run: |
        PID=$(lsof -t -i:8005 -sTCP:LISTEN) || true
        if [ -z "$PID" ]; then
          echo "No process found on port 8005. Proceeding to start the app."
        else
          echo "Killing process on port 8005 with PID $PID"
          kill $PID
        fi
    
    - name: Run app.py in refinement environment
      run: |
        source ~/anaconda3/etc/profile.d/conda.sh
        conda activate refinement
        python /home/dva4/DVA_LAB/models/refiner/app.py
